### PR TITLE
Configure Simple Gauges to Work Like Instrument Panel

### PR DESCRIPTION
**Pull request by timmathews**
This update hides the connection form by default, fixes the log display
functionality, and uses a bit of flexbox to spread out the gauges.

### CODE REVIEW

**Comment by timmathews** [comment]
Currently deployed on demo.signalk.org

**Comment by tkurki** [comment]
I have assumed the implicit practice of not adding the .map files to the repo. They tend to be pretty bi and for the normal end user add very little value. The developer can always regenerate it.

What do you think of this policy? It has been implicit - adding it to .gitignore would make it formal, which I think would be a good idea. Another script entry that doesn't even generate it in package.json might be in order as well - using that as the published version would also skip extra http request for the map.

From dist/gauges.js contents & size it looks like you committed the development version, which is not minified and about three times in size compared to the minified version.

Ping @fabdrol

**Comment by timmathews** [comment]
OK, removed .map and minified gauges.js.

Can't we just drop `--devtool source-map` from the `build` command? `watch` generates a map and is likely what a dev would be using anyway.

**Comment by tkurki** [comment]
Yes, let's do that.

**Comment by tkurki** [comment]
Sorry about letting this rot - what do you feel we should do about it?

**Comment by tkurki** [comment]
To forget or to fix?

**Comment by tkurki** [comment]
Closing for no action.

**Pull request closed without merging**
